[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
noLigation = true

[buildPlans.IosevkaCustom.widths.Normal]
shape = 600
menu = 5
css = "normal"
