[colors.primary]
foreground = "#bdbdbd"
background = "#080808"

[colors.cursor]
cursor = "#9e9e9e"
text = "#080808"

[colors.normal]
black = "#323437"
red = "#ff5454"
green = "#8cc85f"
yellow = "#e3c78a"
blue = "#80a0ff"
magenta = "#cf87e8"
cyan = "#79dac8"
white = "#c6c6c6"

[colors.bright]
black = "#949494"
red = "#ff5189"
green = "#36c692"
yellow = "#c2c292"
blue = "#74b2ff"
magenta = "#ae81ff"
cyan = "#85dc85"
white = "#e4e4e4"

# [colors.search.focused_match]
# background = "#000000"
# foreground = "#cccccc"

# [colors.search.matches]
# background = "#cccccc"
# foreground = "#000000"

[colors.selection]
background = "#b2ceee"
text = "#080808"

[colors.vi_mode_cursor]
cursor = "#b2ceee"
text = "#080808"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "Iosevka Custom"
style = "Regular"

[mouse]
hide_when_typing = true

[shell]
program = "zsh"

[window]
decorations = "Full"
dynamic_padding = false
dynamic_title = false
title = "Terminal"

[window.dimensions]
columns = 179
lines = 60

[window.padding]
x = 3
y = 3
