[general]
import = ["one_dark.toml"]

[font]
size = 12

[font.normal]
family = "Iosevka Custom"
style = "Regular"

[mouse]
hide_when_typing = true

[terminal.shell]
program = "zsh"

[window]
decorations = "Full"
dynamic_padding = false
dynamic_title = false
title = "Terminal"

[window.dimensions]
columns = 120
lines = 45

[window.padding]
x = 10
y = 7
